# Generated by Django 5.2.9 on 2025-12-06 13:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingPool',
            fields=[
                ('pool_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_funds', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('allocated_funds', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('replenished_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wallet_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255, unique=True)),
                ('balance', models.DecimalField(decimal_places=8, default=0.0, help_text='Read-only cache of on-chain balance', max_digits=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen'), ('flagged', 'Flagged')], db_index=True, default='active', max_length=10)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('donor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('reputation_score', models.FloatField(default=0.0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor', to='base.wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('proposal_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('funded', 'Funded')], db_index=True, default='pending', max_length=10)),
                ('funding_goal', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('total_donations', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='base.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('round_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('upcoming', 'Upcoming')], default='upcoming', max_length=10)),
                ('matching_pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='base.matchingpool')),
            ],
        ),
        migrations.AddField(
            model_name='proposal',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='base.round'),
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('payout_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('tx_hash', models.CharField(db_index=True, max_length=255, unique=True)),
                ('distributed_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='base.proposal')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='base.round')),
            ],
        ),
        migrations.CreateModel(
            name='ContractEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('tx_hash', models.CharField(db_index=True, max_length=255, unique=True)),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_events', to='base.proposal')),
                ('round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_events', to='base.round')),
            ],
        ),
        migrations.CreateModel(
            name='QFResult',
            fields=[
                ('result_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calculated_match', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('verified', models.BooleanField(default=False)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qf_results', to='base.proposal')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qf_results', to='base.round')),
            ],
            options={
                'unique_together': {('round', 'proposal')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matched_amount', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='base.proposal')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='base.round')),
            ],
            options={
                'unique_together': {('proposal', 'round')},
            },
        ),
        migrations.CreateModel(
            name='SybilScore',
            fields=[
                ('score_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField(default=0.0)),
                ('verified_by', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sybil_scores', to='base.wallet')),
            ],
            options={
                'unique_together': {('wallet', 'verified_by')},
            },
        ),
        migrations.CreateModel(
            name='GovernanceToken',
            fields=[
                ('holder_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voting_power', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('role', models.CharField(choices=[('member', 'Member'), ('admin', 'Admin'), ('council', 'Council')], default='member', max_length=10)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governance_tokens', to='base.wallet')),
            ],
            options={
                'unique_together': {('wallet', 'role')},
            },
        ),
    ]
