# Generated by Django 5.2.9 on 2025-12-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='on_chain_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
