# Generated by Django 5.2.9 on 2025-12-07 13:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_materialized_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChainSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grant_registry_address', models.CharField(help_text='Address of GrantRegistry contract for this session', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='contractevent',
            name='tx_hash',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='on_chain_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractevent',
            name='chain_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_events', to='base.chainsession'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='chain_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='base.chainsession'),
        ),
    ]
