# Generated by Django 5.2.9 on 2025-12-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_chain_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='chainsession',
            name='deployment_block',
            field=models.IntegerField(default=0, help_text='Block number when GrantRegistry was deployed'),
        ),
        migrations.AlterField(
            model_name='chainsession',
            name='grant_registry_address',
            field=models.CharField(help_text='Address of GrantRegistry contract for this session', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='chainsession',
            unique_together={('grant_registry_address', 'deployment_block')},
        ),
    ]
