# Generated by Django 6.0 on 2025-12-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_chain_session_deployment_block'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chainsession',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='chainsession',
            name='deployment_block_hash',
            field=models.CharField(default='', help_text='Hash of deployment block - unique per node session', max_length=66),
        ),
        migrations.AlterUniqueTogether(
            name='chainsession',
            unique_together={('grant_registry_address', 'deployment_block_hash')},
        ),
    ]
